-- MySQL Script generated by MySQL Workbench
-- Mon Apr 18 18:45:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sklad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sklad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sklad` DEFAULT CHARACTER SET utf8 ;
USE `sklad` ;

-- -----------------------------------------------------
-- Table `sklad`.`zbozi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklad`.`zbozi` (
  `idzbozi` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `znacka` VARCHAR(45) NOT NULL,
  `cena` INT NOT NULL,
  `pocet` INT NOT NULL,
  PRIMARY KEY (`idzbozi`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sklad`.`zbozi`
-- -----------------------------------------------------
START TRANSACTION;
USE `sklad`;
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (1, 'Classic Destination Tee', 'Reebok', 800, 19);
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (2, 'Vocabulary T-Shirt', 'PLEASURES', 1300, 50);
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (3, 'RWB Graphic T-Shirt', 'Helly Hansen', 1000, 25);
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (4, 'Ozelia', 'adidas Originals', 2900, 10);
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (5, 'M5740CBC', 'New Balance', 2849, 14);
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (6, 'Dunk Scrap', 'Nike', 2999, 5);
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (7, 'Promise Pinstripe Pant', 'PLEASURES', 2999, 10);
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (8, 'Puma x Minecraft Sweatpants', 'Puma', 1899, 8);
INSERT INTO `sklad`.`zbozi` (`idzbozi`, `nazev`, `znacka`, `cena`, `pocet`) VALUES (9, 'Simple Pant', 'Carhartt WIP', 1799, 2);

COMMIT;

